float pow2(float x) {return x*x;}
float pow3(float x) {return x*x*x;}
float pow4(float x) {return x*x*x*x;}
float pow5(float x) {return x*x*x*x*x;}
float pow6(float x) {return x*x*x*x*x*x;}
float pow7(float x) {return x*x*x*x*x*x*x;}
float pow8(float x) {return x*x*x*x*x*x*x*x;}
float pow9(float x) {return x*x*x*x*x*x*x*x*x;}
float pow10(float x) {return x*x*x*x*x*x*x*x*x*x;}
float pow11(float x) {return x*x*x*x*x*x*x*x*x*x*x;}
float pow12(float x) {return x*x*x*x*x*x*x*x*x*x*x*x;}
float pow13(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow14(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow15(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow16(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow17(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow18(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow19(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow20(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
float pow24(float x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}

vec2 pow2(vec2 x) {return x*x;}
vec2 pow3(vec2 x) {return x*x*x;}
vec2 pow4(vec2 x) {return x*x*x*x;}
vec2 pow5(vec2 x) {return x*x*x*x*x;}
vec2 pow6(vec2 x) {return x*x*x*x*x*x;}
vec2 pow7(vec2 x) {return x*x*x*x*x*x*x;}
vec2 pow8(vec2 x) {return x*x*x*x*x*x*x*x;}
vec2 pow9(vec2 x) {return x*x*x*x*x*x*x*x*x;}
vec2 pow10(vec2 x) {return x*x*x*x*x*x*x*x*x*x;}
vec2 pow11(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow12(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow13(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow14(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow15(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow16(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow17(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow18(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow19(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow20(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec2 pow24(vec2 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}

vec3 pow2(vec3 x) {return x*x;}
vec3 pow3(vec3 x) {return x*x*x;}
vec3 pow4(vec3 x) {return x*x*x*x;}
vec3 pow5(vec3 x) {return x*x*x*x*x;}
vec3 pow6(vec3 x) {return x*x*x*x*x*x;}
vec3 pow7(vec3 x) {return x*x*x*x*x*x*x;}
vec3 pow8(vec3 x) {return x*x*x*x*x*x*x*x;}
vec3 pow9(vec3 x) {return x*x*x*x*x*x*x*x*x;}
vec3 pow10(vec3 x) {return x*x*x*x*x*x*x*x*x*x;}
vec3 pow11(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow12(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow13(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow14(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow15(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow16(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow17(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow18(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow19(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow20(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}
vec3 pow24(vec3 x) {return x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x*x;}

float sum2(float x) {return x+x;}
float sum3(float x) {return x+x+x;}
float sum4(float x) {return x+x+x+x;}
float sum5(float x) {return x+x+x+x+x;}
float sum6(float x) {return x+x+x+x+x+x;}
float sum7(float x) {return x+x+x+x+x+x+x;}
float sum8(float x) {return x+x+x+x+x+x+x+x;}