item.3=glow_lichen sea_pickle
item.4=brewing_stand
item.5=torchflower torch lantern
item.6=soul_torch soul_lantern soul_fire
item.7=end_rod
item.8=sea_lantern
item.9=glowstone
item.10=shroomlight
item.11=crying_obsidian
item.12=lava_bucket
item.13=glow_berries
item.14=small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster
item.21=magma_block blaze_rod blaze_powder
item.22=emerald_ore deepslate_emerald_ore
item.23=diamond_ore deepslate_diamond_ore
item.24=copper_ore deepslate_copper_ore
item.25=lapis_ore deepslate_lapis_ore
item.26=gold_ore deepslate_gold_ore
item.27=iron_ore deepslate_iron_ore
item.28=redstone_ore deepslate_redstone_ore
item.29=redstone_block redstone_torch
item.32=ochre_froglight
item.33=verdant_froglight
item.34=pearlescent_froglight
item.35=poppy red_tulip red_double_flower red_hibiscus red_lotus_flower red_mystical_flower
item.36=pink_petals pink_tulip flowering_azalea spore_blossom allium pink_clover pink_daffodil pink_delphinium pink_double_flower pink_hibiscus pink_mushroom pink_mystical_flower magenta_hibiscus magenta_mushroom magenta_mystical_flower purple_delphinium purple_double_flower purple_hibiscus purple_hibiscus purple_mushroom purple_mystical_flower purple_wisteria_sapling 
item.37=dandelion yellow_double_flower yellow_hibiscus yellow_mushroom yellow_mystical_flower
item.38=blue_orchid cornflower blue_delphinium blue_double_flower blue_hydrangea blue_mushroom blue_mystical_flower blue_wisteria_sapling light_blue_double_flower light_blue_mushroom light_blue_mystical_flower
item.39=azure_bluet lily_of_the_valley oxeye_daisy white_tulip white_clover white_delphinium white_double_flower white_lotus_flower white_mushroom white_mystical_flower white_searocket white_wisteria_sapling
item.40=orange_tulip orange_double_flower orange_hibiscus orange_mushroom orange_mystical_flower
item.41=jack_o_lantern
item.42=enchanting_table
item.60=beacon
item.65=crimson_stem crimson_hyphae
item.66=warped_stem warped_hyphae 
item.80=chorus_flower
item.83=copper_torch copper_lantern exposed_copper_lantern waxed_copper_lantern waxed_exposed_copper_lantern

item.1502=iron_shovel iron_pickaxe iron_axe iron_hoe iron_sword iron_spear iron_helmet iron_chestplate iron_leggings iron_boots iron_ingot iron_nugget iron_horse_armor shears
item.1503=golden_shovel golden_pickaxe golden_axe golden_hoe golden_sword golden_spear golden_helmet golden_chestplate golden_leggings golden_boots gold_ingot gold_nugget golden_apple enchanted_golden_apple golden_carrot golden_horse_armor
item.1504=diamond_shovel diamond_pickaxe diamond_axe diamond_hoe diamond_sword diamond_spear diamond_helmet diamond_chestplate diamond_leggings diamond_boots diamond diamond_horse_armor emerald
item.1505=ender_pearl ender_eye

item.11001=trim_emerald trim_redstone trim_lapis trim_amethyst trim_quartz trim_netherite trim_diamond trim_gold trim_iron trim_copper trim_resin
item.1506=copper_shovel copper_pickaxe copper_axe copper_hoe copper_sword copper_spear copper_helmet copper_chestplate copper_leggings copper_boots copper_ingot raw_copper copper_nugget

item.1507=iron_block heavy_weighted_pressure_plate iron_door iron_trapdoor chain hopper cauldron anvil chipped_anvil damaged_anvil
item.1508=gold_block light_weighted_pressure_plate bell clock
item.1509=diamond_block emerald_block
item.1510=chiseled_copper exposed_chiseled_copper oxidized_chiseled_copper weathered_chiseled_copper waxed_chiseled_copper waxed_exposed_chiseled_copper waxed_oxidized_chiseled_copper waxed_weathered_chiseled_copper copper_block cut_copper cut_copper_stairs cut_copper_slab waxed_copper_block waxed_exposed_copper waxed_weathered_copper waxed_cut_copper waxed_exposed_cut_copper waxed_weathered_cut_copper waxed_oxidized_cut_copper waxed_cut_copper_stairs waxed_exposed_cut_copper_stairs waxed_weathered_cut_copper_stairs waxed_oxidized_cut_copper_stairs waxed_cut_copper_slab waxed_exposed_cut_copper_slab waxed_weathered_cut_copper_slab waxed_oxidized_cut_copper_slab waxed_oxidized_copper lightning_rod copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb copper_grate exposed_copper_grate weathered_copper_grate oxidized_copper_grate waxed_copper_grate waxed_exposed_copper_grate waxed_weathered_copper_grate waxed_oxidized_copper_grate copper_door exposed_copper_door weathered_copper_door oxidized_copper_door waxed_copper_door waxed_exposed_copper_door waxed_weathered_copper_door waxed_oxidized_copper_door copper_trapdoor exposed_copper_trapdoor weathered_copper_trapdoor oxidized_copper_trapdoor waxed_copper_trapdoor waxed_exposed_copper_trapdoor waxed_weathered_copper_trapdoor waxed_oxidized_copper_trapdoor
item.1511=raw_iron_block raw_gold_block raw_copper_block
item.1512=netherite_ingot netherite_scrap netherite_block netherite_shovel netherite_pickaxe netherite_axe netherite_hoe netherite_sword netherite_spear netherite_helmet netherite_chestplate netherite_leggings netherite_boots
